

server:
  port: 8080



#File upload configuration
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: VideoStreamingApp
  #database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/videostreaming
    username: postgres
    password: root
   #jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true
       use_sql_comments: true




#Custom configuration
app:
  video:
    upload-dir: uploads/videos
    hls-dir: uploads/hls
  ffmpeg:
    path:
    ffprobe:
logging:
  level:
    root: INFO
    com.example.videostreaminghls: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
